[package]
name = "steal_stickers_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
telers = "1.0.0-alpha.20"
tokio = { version = "1.36", features = ["macros"]}
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] } 